[x] configure.ac - added --enable-prelude, for now it does not really work   - libprelude-config does not provide the inclusion path for the headers, so its pretty useless [x] log-prelude - added Makefile.am - included config.h in log-prelude.hpp - hopefully log-prelude.cpp exists with a warning when compiled without prelude
I cant check this code really works, as
/usr/include/libprelude/prelude-error.h: In function 'prelude_bool_t prelude_error_is_verbose(prelude_error_t)':
/usr/include/libprelude/prelude-error.h:405: error: invalid conversion from 'int' to 'prelude_bool_t'

prevents me from compiling it myself (...)